# Generated by Django 2.2.6 on 2019-12-23 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quetions',
            new_name='Questions',
        ),
    ]
