# Generated by Django 2.2.6 on 2019-12-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20191223_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='q1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='q2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='q3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='q4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quest1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quest2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quest3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quest4',
            field=models.CharField(max_length=500),
        ),
    ]
