# Generated by Django 2.2.6 on 2019-12-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20191223_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='q1',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q2',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q3',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q4',
            new_name='D',
        ),
    ]
