# Generated by Django 2.2.6 on 2019-12-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20191223_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='A',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='B',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='C',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='D',
            field=models.BooleanField(),
        ),
    ]
