# Generated by Django 2.2.6 on 2019-12-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20191223_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chosen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questpack', models.CharField(max_length=500)),
                ('A', models.CharField(max_length=500)),
                ('B', models.CharField(max_length=500)),
                ('C', models.CharField(max_length=500)),
                ('D', models.CharField(max_length=500)),
                ('truequest', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
