# Generated by Django 2.2.6 on 2019-12-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosen',
            name='AB',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='chosen',
            name='BB',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='chosen',
            name='CB',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='chosen',
            name='DB',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='questions',
            name='AB',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='questions',
            name='BB',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='questions',
            name='CB',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='questions',
            name='DB',
            field=models.BooleanField(default=None),
        ),
    ]
