# Generated by Django 2.2.6 on 2019-12-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20191225_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='AB',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='BB',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='CB',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='DB',
        ),
    ]
