# Generated by Django 2.2.6 on 2019-12-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20191225_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosen',
            name='AB',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chosen',
            name='BB',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chosen',
            name='CB',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chosen',
            name='DB',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
