# Generated by Django 2.2.6 on 2019-12-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20191226_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosen',
            name='none',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
