# Generated by Django 2.2.6 on 2019-12-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_chosen_none'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='chosen',
            name='none',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
