# Generated by Django 2.2.6 on 2020-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20191229_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password2',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=90, unique=True),
        ),
    ]
