# Generated by Django 2.2.6 on 2020-01-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20200105_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password2',
        ),
    ]
